<?php

namespace Ens\JobeetBundle\Extension;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-19 at 22:34:18.
 */
class W3FiltersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var W3Filters
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new W3Filters;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Ens\JobeetBundle\Extension\W3Filters::slug
     * @todo   Implement testSlug().
     */
    public function testSlug()
    {
        $this->assertEquals('sensio', W3Filters::slug('Sensio'));
        $this->assertEquals('sensio-labs', W3Filters::slug('sensio labs'));
        $this->assertEquals('sensio-labs', W3Filters::slug('sensio   labs'));
        $this->assertEquals('paris-france', W3Filters::slug('paris,france'));
        $this->assertEquals('sensio', W3Filters::slug('  sensio'));
        $this->assertEquals('sensio', W3Filters::slug('sensio  '));
    }
    
}
